### ISSUE TITLE
Provide simple routing

### ISSUE THREAD

**Issue by darkwing** [mozilla-neutrino/neutrino-preset-web#10]
As of right now, `index.js` is where dynamic/react page content is meant to be generated.

I'd like to propose that we create intelligent but basic routing to JS file name.  For example, if someone has a `test-page.js` file, `/test-page` would render what `test-page.js` directed.  I basically just want to expand the `index` pattern elsewhere.

**Comment by eliperelman** [comment]
My concern is that approach is kinda application specific. For example, would this router be implemented in Node? How would it work when spinning up the Webpack Dev Server? How would it run when built to static assets? Static assets won't be running Node, so then the implementation should be a client side router? If that's the case, how do you effectively use the file system as the client side routing? How do all these things differ when using React vs. Angular vs. Vanilla, etc.?

So this is a problem that can be solved, I'm just not sure what the right answer is, and if there is an answer that would be relatively application-agnostic and easily overridable without introducing project boilerplate.

For reference, we used to provide [boilerplate through the Neo project](https://github.com/mozilla/neo/tree/master/commands/init/templates/src), but it was a large tradeoff between ease of project setup and easy configuration because then source files would either have to change or be deleted to use the project the way you wanted. I want to be careful that if we go down this route that we don't inject boilerplate into projects.

**Comment by eliperelman** [comment]
Since this is application-specific boilerplate, I'm going to close as this should be in app code rather than build code.
